config/routes.rb
Rails.application.routes.draw do
  get 'days/index'

  get 'energies/index'

  get 'energies/import'

  #get 'onduleur_energy/index'

  #get 'onduleur_energy/import'

  resources :onduleurs
  resources :energies do 
  	collection { post :import, :search }
  end 
  resources :days

  root to: "energies#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/day.rb
class Day < ApplicationRecord
	
	belongs_to :onduleur
	require 'ransack'
end

app/models/energy.rb
class Energy < ApplicationRecord
	belongs_to :onduleur
	require 'csv'
	require 'ransack'

	after_create do 
		puts "Debut after_create"
		p self.onduleur_id
		p self.date.to_date
		if (Day.where(:onduleur_id => self.onduleur_id, :date => self.date.to_date).exists?)
			puts "then after_create 1"
			day = Day.where(:onduleur_id => self.onduleur_id, :date => self.date.to_date).first
			puts "then after_create 2"
			#day.energie =  day.energie + self.energie
			day.increment(:energie, self.energie)
			puts "then after_create 3"
			day.save
			puts "then after_create 4"
		else 
			puts "else after_create"
			Day.create(:onduleur_id => self.onduleur_id, :date => self.date.to_date, energie: self.energie)
		end

	end 

	def self.import(file)
		puts file.path
		CSV.foreach(file.path, {:headers => true, :col_sep => ","}) do |row|
			#identifier, datetime, energy = row
			#puts "#{identifier}, #{datetime}, #{energy}"
			if (row["identifier"] != nil)
				if Energy.where(:onduleur_id => row["identifier"], :date => DateTime.strptime(row["datetime"],"%d/%m/%y %H:%M")).exists? 
					puts "Enregistrement déjà existant"
				else 
					puts "On insère en base"
					energy = Energy.create(onduleur_id: row["identifier"], date: DateTime.strptime(row["datetime"],"%d/%m/%y %H:%M"), energie: row["energy"])
				end 
			end		
			#counter += 1 if onduleurEnergy.persisted?

		end
		#puts "#{counter} lignes importées"
	end
end

app/models/onduleur.rb
class Onduleur < ApplicationRecord
	has_many :energy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
   def index
  	#p params[:q]
  	@search = Day.search(params[:q])
    @days = @search.result
	# Initial
	#@energies = Energie.all
  end
end

app/controllers/energies_controller.rb
class EnergiesController < ApplicationController
  def index
  	p params[:q]
  	@search = Energy.search(params[:q])
    @energies = @search.result
	# Initial
	#@energies = Energie.all
  end

  def import
	begin 
		Energy.import(params[:file]) 
		redirect_to root_url, notice: "Energies importés !!!"
	rescue 
		redirect_to root_url, notice: "Format CSV invalide"
	end 
	
  end
end

app/controllers/onduleurs_controller.rb
class OnduleursController < ApplicationController
  before_action :set_onduleur, only: [:show, :edit, :update, :destroy]

  # GET /onduleurs
  # GET /onduleurs.json
  def index
    @onduleurs = Onduleur.all
  end

  # GET /onduleurs/1
  # GET /onduleurs/1.json
  def show
  end

  # GET /onduleurs/new
  def new
    @onduleur = Onduleur.new
  end

  # GET /onduleurs/1/edit
  def edit
  end

  # POST /onduleurs
  # POST /onduleurs.json
  def create
    @onduleur = Onduleur.new(onduleur_params)

    respond_to do |format|
      if @onduleur.save
        format.html { redirect_to @onduleur, notice: 'Onduleur was successfully created.' }
        format.json { render :show, status: :created, location: @onduleur }
      else
        format.html { render :new }
        format.json { render json: @onduleur.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /onduleurs/1
  # PATCH/PUT /onduleurs/1.json
  def update
    respond_to do |format|
      if @onduleur.update(onduleur_params)
        format.html { redirect_to @onduleur, notice: 'Onduleur was successfully updated.' }
        format.json { render :show, status: :ok, location: @onduleur }
      else
        format.html { render :edit }
        format.json { render json: @onduleur.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /onduleurs/1
  # DELETE /onduleurs/1.json
  def destroy
    @onduleur.destroy
    respond_to do |format|
      format.html { redirect_to onduleurs_url, notice: 'Onduleur was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_onduleur
      @onduleur = Onduleur.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def onduleur_params
      params.require(:onduleur).permit(:lb, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/energies_helper.rb
module EnergiesHelper
end

app/helpers/onduleurs_helper.rb
module OnduleursHelper
end

app/views/days/index.html.erb
<%= search_form_for @search do |f| %>
	<div class="row">

		<%= f.label 'Date' %>
	  	<%= f.date_select :date_gteq,  {:order=>[:day,:month,:year] ,  :default => @the_date, :include_blank=> @the_date.nil? , :use_month_names => [nil,"janvier","février","mars","avril","mai","juin","juillet","août","septembre","octobre","novembre","décembre"]} %>
	  	<%= f.date_select :date_lteq,  {:order=>[:day,:month,:year] ,  :default => @the_date, :include_blank=> @the_date.nil? , :use_month_names => [nil,"janvier","février","mars","avril","mai","juin","juillet","août","septembre","octobre","novembre","décembre"]} %>
	  	<%= f.submit "Search" %>
	</div>
<% end %>
<%= flash[:notice] %>
<table>
	<thead>
		<tr>
			<th>Onduleur</th>
			<th>date</th>
			<th>Energie</th>
		</tr>
	</thead>
	<tbody>
		<% @days.each do |day| %>
		<tr>
			<td><%= day.onduleur_id %></td>
			<td><%= day.date.strftime("%d/%m/%y") %></td>
			<td><%= day.energie %></td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/energies/import.html.erb
<h1>Energies#import</h1>
<p>Find me in app/views/energies/import.html.erb</p>

app/views/energies/index.html.erb
<style>
   .calender-span {
    float: right;
    margin-right: 6px;
    margin-top: -20px;
    position: relative;
    z-index: 2;
    color: red;
   }

</style>


<%= search_form_for @search do |f| %>
	<div class="row">

		<%= f.label 'Date' %>
	  	<%= f.datetime_select :date_gteq,  {:order=>[:day,:month,:year] ,  :default => @the_date, :include_blank=> @the_date.nil? , :use_month_names => [nil,"janvier","février","mars","avril","mai","juin","juillet","août","septembre","octobre","novembre","décembre"]}  %>
	  	<%= f.datetime_select :date_lteq,  {:order=>[:day,:month,:year] ,  :default => @the_date, :include_blank=> @the_date.nil? , :use_month_names => [nil,"janvier","février","mars","avril","mai","juin","juillet","août","septembre","octobre","novembre","décembre"]}  %>
	  	<%= f.submit "Search" %>
	</div>
<% end %>
<%= flash[:notice] %>
<table>
	<thead>
		<tr>
			<th>Onduleur</th>
			<th>date</th>
			<th>Energie</th>
		</tr>
	</thead>
	<tbody>
		<% @energies.each do |energie| %>
		<tr>
			<td><%= energie.onduleur_id %></td>
			<td><%= energie.date.strftime("%d/%m/%y %H:%M") %></td>
			<td><%= energie.energie %></td>
		</tr>
		<% end %>
	</tbody>
</table>
<div>
	<h3>Import a CSV File</h3>
	<%= form_tag import_energies_path, multipart: true do %>
	<%= file_field_tag :file %>
	<%= submit_tag "Import CSV" %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hespul</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/onduleurs/_form.html.erb
<%= form_for(onduleur) do |f| %>
  <% if onduleur.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(onduleur.errors.count, "error") %> prohibited this onduleur from being saved:</h2>

      <ul>
      <% onduleur.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lb %>
    <%= f.text_field :lb %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/onduleurs/edit.html.erb
<h1>Editing Onduleur</h1>

<%= render 'form', onduleur: @onduleur %>

<%= link_to 'Show', @onduleur %> |
<%= link_to 'Back', onduleurs_path %>

app/views/onduleurs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Onduleurs</h1>

<table>
  <thead>
    <tr>
      <th>Lb</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @onduleurs.each do |onduleur| %>
      <tr>
        <td><%= onduleur.lb %></td>
        <td><%= onduleur.description %></td>
        <td><%= link_to 'Show', onduleur %></td>
        <td><%= link_to 'Edit', edit_onduleur_path(onduleur) %></td>
        <td><%= link_to 'Destroy', onduleur, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Onduleur', new_onduleur_path %>

app/views/onduleurs/new.html.erb
<h1>New Onduleur</h1>

<%= render 'form', onduleur: @onduleur %>

<%= link_to 'Back', onduleurs_path %>

app/views/onduleurs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lb:</strong>
  <%= @onduleur.lb %>
</p>

<p>
  <strong>Description:</strong>
  <%= @onduleur.description %>
</p>

<%= link_to 'Edit', edit_onduleur_path(@onduleur) %> |
<%= link_to 'Back', onduleurs_path %>